# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Notes
  pod "cloudrail-si-ios-sdk"
  pod 'ObjectiveDropboxOfficial'
  
  target 'NotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
